language: minimal
os: linux
dist: trusty
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
script:
  - chmod +x ./deploy-envs.sh
  - chmod +x ./docker-entrypoint.sh
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/deploy.sh
  - cd scripts && ./build.sh
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi