version: '3'

services:
  reverse-proxy:
    image: containous/traefik
    command: --configFile=/traefik.toml
    ports:
      - "5000:80"
    volumes:
      - "./traefik.toml:/traefik.toml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    labels:
      - "traefik.frontend=traefikAPI"

  whoami1:
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Path:/whoami1"

  whoami2:
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Path:/whoami2"