[web]
address = ":8080"
readOnly = true
[web.metrics.prometheus]
buckets=[0.1,0.3,1.2,5.0]


[ecs]
clusters = ["AWS_ECS_CLUSTER_NAME"]
watch = true
domain = "AWS_VIRTUAL_HOST"
autoDiscoverClusters = false
refreshSeconds = 15
exposedByDefault = true
region = "AWS_DEFAULT_REGION"