#!/bin/bash
source ../deploy-envs.sh

docker run -d \
-e AWS_ECS_CLUSTER_NAME=$AWS_ECS_CLUSTER_NAME \
-e AWS_VIRTUAL_HOST=$AWS_VIRTUAL_HOST \
-e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
-p 8080:8080 \
-p 5000:80 \
$IMAGE_NAME $AWS_ECS_REPO_DOMAIN/$IMAGE_NAME:$IMAGE_VERSION